use crate::episode_store::EpisodeStore;
use crate::types::{CotEntry, MarketRegime, PortfolioState, TradeSignal};
use chrono::{DateTime, Utc};
use std::collections::HashMap;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use tokio::sync::RwLock;
use tredo_core::{
    CalendarEvent, Config, DisciplineRules, LlmExecutor, MemoryStore, NewsContext, OhlcvBar,
    PivotLevels, SkillVote, TradingGoals, VectorMemory,
};
use tredo_core::{CandlestickPattern, MultiTfPatternConfirmation};
use tredo_core::paper_engine::{BrokerRegistry, PaperEngineConfig};

/// Maximum COT entries kept in RAM before flushing to SQLite.
const MAX_COT_RAM: usize = 50;

/// Multi-timeframe market data for a single symbol
#[derive(Debug, Clone)]
pub struct TimeframeData {
    pub timeframe: String, // "1m", "15m", "1h", "1d"
    pub ohlcv: Vec<OhlcvBar>,
    pub pivots: Option<PivotLevels>,
    pub confluence: f64,
    pub last_updated: DateTime<Utc>,
}

/// A scheduled task for the agent to execute at specific intervals
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AgentTask {
    pub name: String,
    pub interval_secs: u64,
    pub last_run: Option<DateTime<Utc>>,
    pub enabled: bool,
}

impl AgentTask {
    pub fn new(name: &str, interval_secs: u64) -> Self {
        Self {
            name: name.to_string(),
            interval_secs,
            last_run: None,
            enabled: true,
        }
    }

    pub fn should_run(&self, now: &DateTime<Utc>) -> bool {
        if !self.enabled {
            return false;
        }
        match self.last_run {
            Some(last) => (*now - last).num_seconds() as u64 >= self.interval_secs,
            None => true,
        }
    }
}

#[derive(Debug, Clone)]
pub struct SharedState {
    pub portfolio: Arc<RwLock<PortfolioState>>,
    pub memory: Arc<MemoryStore>,
    pub rules: Arc<RwLock<DisciplineRules>>,
    pub config: Arc<Config>,
    pub last_signals: Arc<RwLock<Vec<TradeSignal>>>,
    pub market_regime: Arc<RwLock<Option<MarketRegime>>>,
    pub llm: Arc<LlmExecutor>,
    /// Kronos forecast stored by MarketIntelligenceAgent (Phase 2) for use in StrategyDecisionAgent (Phase 5).
    pub last_forecast: Arc<RwLock<Option<serde_json::Value>>>,
    /// LLM reasoning from last cycle — stored for debugging / UI display.
    pub last_llm_reason: Arc<RwLock<String>>,
    /// Historical OHLCV data per symbol (1m) — capped at MAX_OHLCV_BARS per symbol.
    pub ohlcv_history: Arc<RwLock<HashMap<String, Vec<OhlcvBar>>>>,

    // ── 24/7 Agentic AI System Additions ──
    /// Economic calendar — upcoming high-impact events the agent should know about.
    pub calendar_events: Arc<RwLock<Vec<CalendarEvent>>>,
    /// Trading goals — targets and behavior mode the agent references for decisions.
    pub trading_goals: Arc<RwLock<TradingGoals>>,
    /// Dynamic watchlist — symbols the agent is currently monitoring.
    pub watchlist: Arc<RwLock<Vec<String>>>,
    /// Multi-timeframe OHLCV data (15m, 1h, 1d) per symbol.
    pub multi_timeframe_data: Arc<RwLock<HashMap<String, Vec<TimeframeData>>>>,
    /// Scheduled agent tasks for different workflows.
    pub agent_tasks: Arc<RwLock<Vec<AgentTask>>>,
    /// Last full-scan timestamp for the watchlist scanner.
    pub last_watchlist_scan: Arc<RwLock<Option<DateTime<Utc>>>>,
    /// The agent's latest summary of market conditions (generated by LLM reflection).
    pub agent_market_summary: Arc<RwLock<String>>,

    /// Latest episode ID per symbol — used to update outcomes when trades close.
    pub latest_episode: Arc<RwLock<HashMap<String, String>>>,

    /// Latest news context per symbol — fetched by NewsFetcher, injected into LLM prompts.
    pub latest_news: Arc<RwLock<HashMap<String, NewsContext>>>,

    /// Vector memory for semantic similarity search across episodes (now LanceDB backed for production).
    pub vector_memory: Arc<tokio::sync::Mutex<tredo_core::VectorMemory>>,

    /// Latest detected candlestick patterns per symbol — populated by MarketIntelligenceAgent.
    pub last_patterns: Arc<RwLock<HashMap<String, Vec<CandlestickPattern>>>>,

    /// Multi-timeframe pattern confirmation per symbol — cross-references patterns across timeframes.
    pub last_mtf_patterns: Arc<RwLock<HashMap<String, MultiTfPatternConfirmation>>>,

    /// Chain-of-thought store — capped at MAX_COT_RAM entries in RAM; older entries flushed to SQLite.
    pub cot_store: Arc<RwLock<Vec<CotEntry>>>,
    /// Atomic counter for generating unique COT entry IDs.
    pub cot_id_counter: Arc<AtomicU64>,

    /// Broadcast channel for real-time WS updates (COT, signals, prices, memory recalls) - connects TUI and clients.
    pub update_tx: Arc<tokio::sync::broadcast::Sender<String>>,
    /// SQLite-backed persistent store for closed trade episodes, regret events, COT logs.
    pub episode_store: Arc<EpisodeStore>,
    /// The most recent skill votes, captured by MarketIntelligenceAgent.
    /// Consumed by OutcomeProcessor when a trade closes.
    pub last_skill_votes: Arc<RwLock<Vec<SkillVote>>>,

    /// The aggregated signal from skills (produced by SkillAggregator in MI).
    /// Now wired into strategy decision for real use of ensemble (previously only in COT).
    pub last_aggregated_signal: Arc<RwLock<Option<tredo_core::AggregatedSignal>>>,

    /// Latest rich metrics snapshot per symbol from MarketMetricsMeter tool (RSI/MACD/ATR/BB/Stoch/vol/regime/fib/confluence).
    /// Connected to pipeline, debate, strategy (autonomous levels), aggregator (via skill), memory recall, WS price updates.
    pub latest_metrics: Arc<RwLock<HashMap<String, crate::market_metrics_meter::MetricsSnapshot>>>,

    /// Broker registry for live trading — routes orders through PaperBroker or Zerodha/other.
    /// When mode is Live, trades are executed on the real exchange via the registered broker adapter.
    pub broker_registry: Arc<BrokerRegistry>,
}

impl SharedState {
    /// Get current skill weights (for FSM coordinator).
    pub fn get_skill_weights(&self) -> std::collections::HashMap<String, f64> {
        let mut weights = std::collections::HashMap::new();
        weights.insert("news_analyser".to_string(), 0.25);
        weights.insert("market_metrics_meter".to_string(), 0.25);
        weights.insert("sentiment_analyzer".to_string(), 0.25);
        weights.insert("on_chain_data".to_string(), 0.25);
        weights
    }

    /// Get current risk config (for FSM coordinator).
    pub fn get_risk_config(&self) -> crate::risk_guardian::RiskGuardianConfig {
        crate::risk_guardian::RiskGuardianConfig::default_fallback()
    }
    pub fn new(
        memory: MemoryStore,
        rules: DisciplineRules,
        config: Config,
        db_path: &str,
    ) -> Result<Self, rusqlite::Error> {
        // Open (or create) SQLite history database (with built-in recovery for locks/WAL)
        let episode_store = Arc::new(EpisodeStore::open(db_path)?);
        let portfolio = PortfolioState {
            cash_balance: config.initial_balance,
            total_equity: config.initial_balance,
            daily_pnl: 0.0,
            daily_pnl_pct: 0.0,
            open_positions: Vec::new(),
            total_trades_today: 0,
            winning_trades_today: 0,
            losing_trades_today: 0,
            consecutive_losses: 0,
            max_drawdown_today: 0.0,
            last_trade_time: None,
            trading_enabled: true,
        };

        // Generate economic calendar at startup
        let calendar = tredo_core::generate_economic_calendar();

        // Default watchlist
        let default_watchlist = Vec::new();

        // Default agent tasks for 24/7 operation
        let tasks = vec![
            AgentTask::new("price_scan", 5),           // Every 5 seconds
            AgentTask::new("position_monitor", 10),    // Every 10 seconds
            AgentTask::new("market_scan", 300),        // Every 5 minutes
            AgentTask::new("portfolio_review", 3600),  // Every hour
            AgentTask::new("goal_review", 43200),      // Every 12 hours
            AgentTask::new("daily_reflection", 86400), // Once per day
        ];

        let (update_tx, _) = tokio::sync::broadcast::channel(256);

        Ok(Self {
            portfolio: Arc::new(RwLock::new(portfolio)),
            memory: Arc::new(memory),
            rules: Arc::new(RwLock::new(rules)),
            config: Arc::new(config),
            last_signals: Arc::new(RwLock::new(Vec::new())),
            market_regime: Arc::new(RwLock::new(None)),
            llm: Arc::new(LlmExecutor::new()),
            last_forecast: Arc::new(RwLock::new(None)),
            last_llm_reason: Arc::new(RwLock::new(String::new())),
            ohlcv_history: Arc::new(RwLock::new(HashMap::new())),
            calendar_events: Arc::new(RwLock::new(calendar)),
            trading_goals: Arc::new(RwLock::new(TradingGoals::default())),
            watchlist: Arc::new(RwLock::new(default_watchlist)),
            multi_timeframe_data: Arc::new(RwLock::new(HashMap::new())),
            agent_tasks: Arc::new(RwLock::new(tasks)),
            last_watchlist_scan: Arc::new(RwLock::new(None)),
            agent_market_summary: Arc::new(RwLock::new(String::new())),
            latest_episode: Arc::new(RwLock::new(HashMap::new())),
            latest_news: Arc::new(RwLock::new(HashMap::new())),
            vector_memory: Arc::new(tokio::sync::Mutex::new(VectorMemory::new(
                "tredo_vectors.json",
            ))), // With `lancedb` feature on tredo-core, first store() lazily creates sibling tredo_vectors.lance/ + migrates JSON (see vector_memory.rs)
            last_patterns: Arc::new(RwLock::new(HashMap::new())),
            last_mtf_patterns: Arc::new(RwLock::new(HashMap::new())),
            cot_store: Arc::new(RwLock::new(Vec::new())),
            cot_id_counter: Arc::new(AtomicU64::new(1)),
            episode_store,
            last_skill_votes: Arc::new(RwLock::new(Vec::new())),
            last_aggregated_signal: Arc::new(RwLock::new(None)),
            latest_metrics: Arc::new(RwLock::new(HashMap::new())),
            update_tx: Arc::new(update_tx),
            broker_registry: Arc::new(BrokerRegistry::new(PaperEngineConfig::default())),
        })
    }
}

impl SharedState {
    /// Push a chain-of-thought entry into the store and return its unique ID.
    #[allow(clippy::too_many_arguments)]
    #[allow(clippy::too_many_arguments)]
    pub async fn push_cot(
        &self,
        agent: &str,
        input: &str,
        action: &str,
        reason: &str,
        confidence: f64,
        chain_id: u64,
        parent_id: Option<u64>,
        symbol: Option<String>,
    ) -> u64 {
        let id = self.cot_id_counter.fetch_add(1, Ordering::Relaxed);
        let entry = CotEntry {
            id,
            chain_id,
            parent_id,
            agent: agent.to_string(),
            input: input.to_string(),
            action: action.to_string(),
            reason: reason.to_string(),
            confidence,
            timestamp: Utc::now().to_rfc3339(),
            symbol,
        };
        let mut store = self.cot_store.write().await;
        store.push(entry.clone());
        let store_len = store.len();
        // Flush oldest entries to SQLite when RAM cap is reached
        if store_len > MAX_COT_RAM {
            let overflow: Vec<_> = store.drain(0..store_len - MAX_COT_RAM).collect();
            let rows: Vec<crate::episode_store::CotLogRow> = overflow
                .iter()
                .map(|e| crate::episode_store::CotLogRow {
                    chain_id: e.chain_id,
                    agent: e.agent.clone(),
                    action: e.action.clone(),
                    reason: e.reason.clone(),
                    confidence: e.confidence,
                    symbol: e.symbol.clone(),
                    ts: e.timestamp.clone(),
                })
                .collect();
            let _ = self.episode_store.flush_cot_batch(&rows);
        }

        // Broadcast for WS real-time (connects to TUI/clients with debate/trained data)
        // Include all fields the COT renderer expects: timestamp, input, id, chain_id, etc.
        let update = serde_json::json!({
            "type": "cot",
            "id": entry.id,
            "chain_id": entry.chain_id,
            "parent_id": entry.parent_id,
            "agent": entry.agent,
            "input": entry.input,
            "action": entry.action,
            "reason": entry.reason,
            "confidence": entry.confidence,
            "timestamp": entry.timestamp,
            "symbol": entry.symbol
        })
        .to_string();
        let _ = self.update_tx.send(update);

        id
    }

    /// Hierarchical memory recall for "smarter" agents: combines local vector RAG (recent trained episodes)
    /// + agentmemory (long-term shared trained lessons across sessions/agents).
    ///
    ///   Returns formatted string for injection into reasoning/prompts/COT so agents "understand exactly what they (or similar) did before and the outcome/lesson".
    ///   This is key to long-term improvement and reducing hallucinations by grounding in real past actions + results.
    pub async fn recall_trained_memory(
        &self,
        query_context: &str, // e.g. "proposed BUY on high vol low corr for BTC"
        top_k: usize,
    ) -> String {
        let mut parts = vec!["── HIERARCHICAL TRAINED MEMORY RECALL ──".to_string()];

        // Local vector RAG (fast, in-process, recent episodes with regret/lessons)
        {
            let vm = self.vector_memory.lock().await;
            if !vm.is_empty() {
                match vm.search(query_context, top_k, &self.llm).await {
                    Ok(results) if !results.is_empty() => {
                        parts.push("LOCAL VECTOR (recent trained episodes):".to_string());
                        for r in results {
                            let regret = r
                                .regret_score
                                .map(|s| format!(" regret={:.2}", s))
                                .unwrap_or_default();
                            parts.push(format!(
                                "  - {} (sim {:.0}%{}): {}",
                                r.timestamp.format("%m/%d"),
                                r.similarity * 100.0,
                                regret,
                                r.summary_text
                            ));
                        }
                    }
                    _ => {}
                }
            }
        }

        // Long-term agentmemory (shared, cross-session "trained intelligence" – lessons, past decisions by this or other agents)
        {
            let mem = tredo_core::AgentMemoryClient::new();
            match mem
                .recall(&format!("trained lesson OR past action {}", query_context))
                .await
            {
                Ok(past) if !past.is_empty() => {
                    parts.push("LONG-TERM AGENTMEMORY (trained lessons across time):".to_string());
                    for p in past.iter().take(top_k) {
                        parts.push(format!("  - {}", p));
                    }
                }
                _ => {}
            }
        }

        if parts.len() == 1 {
            parts.push(
                "No strong trained memory match – proceeding with current rules + data only."
                    .to_string(),
            );
        }

        parts.join("\n")
    }

    /// Start a new COT chain (root node) — creates an entry with chain_id = own id.
    pub async fn start_cot_chain(
        &self,
        agent: &str,
        input: &str,
        action: &str,
        reason: &str,
        confidence: f64,
    ) -> u64 {
        let id = self.cot_id_counter.fetch_add(1, Ordering::Relaxed);
        let entry = CotEntry {
            id,
            chain_id: id,
            parent_id: None,
            agent: agent.to_string(),
            input: input.to_string(),
            action: action.to_string(),
            reason: reason.to_string(),
            confidence,
            timestamp: Utc::now().to_rfc3339(),
            symbol: None,
        };
        let mut store = self.cot_store.write().await;
        store.push(entry);
        let store_len = store.len();
        if store_len > MAX_COT_RAM {
            let overflow: Vec<_> = store.drain(0..store_len - MAX_COT_RAM).collect();
            let rows: Vec<crate::episode_store::CotLogRow> = overflow
                .iter()
                .map(|e| crate::episode_store::CotLogRow {
                    chain_id: e.chain_id,
                    agent: e.agent.clone(),
                    action: e.action.clone(),
                    reason: e.reason.clone(),
                    confidence: e.confidence,
                    symbol: e.symbol.clone(),
                    ts: e.timestamp.clone(),
                })
                .collect();
            let _ = self.episode_store.flush_cot_batch(&rows);
        }
        id
    }

    /// Add a step to an existing COT chain.
    #[allow(clippy::too_many_arguments)]
    pub async fn add_cot_step(
        &self,
        chain_id: u64,
        agent: &str,
        input: &str,
        action: &str,
        reason: &str,
        confidence: f64,
        symbol: Option<String>,
    ) -> u64 {
        self.push_cot(
            agent,
            input,
            action,
            reason,
            confidence,
            chain_id,
            Some(chain_id),
            symbol,
        )
        .await;
        self.cot_id_counter.load(Ordering::Relaxed) - 1
    }
}

pub async fn initialize_autonomous_system(
) -> Result<crate::AutonomousOrchestrator, Box<dyn std::error::Error + Send + Sync>> {
    let memory = MemoryStore::new("tredo.redb")?;
    let rules = DisciplineRules::default();
    let config = Config::default();
    let state = SharedState::new(memory, rules, config, "tredo_history.db")
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })?;
    Ok(crate::AutonomousOrchestrator::new(state))
}
