//! Strategy trait — for defining and composing trading strategies.

use crate::data_feed::Bar;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategySignal {
    pub symbol: String,
    pub direction: SignalDirection,
    pub confidence: f64,
    pub entry_price: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub position_size_pct: f64,
    pub rationale: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SignalDirection {
    Long,
    Short,
    Hold,
}

/// A trading strategy that can be plugged into the runtime.
#[async_trait]
pub trait Strategy: Send + Sync {
    /// Name of the strategy.
    fn name(&self) -> &str;

    /// Evaluate the strategy on the latest bar.
    async fn evaluate(&self, symbol: &str, bar: &Bar, context: &StrategyContext) -> StrategySignal;

    /// Return the maximum number of concurrent positions allowed by this strategy.
    fn max_concurrent_positions(&self) -> usize {
        1
    }
}

/// Context available to strategies during evaluation.
#[derive(Debug, Clone)]
pub struct StrategyContext {
    pub historical_bars: Vec<Bar>,
    pub cash_balance: f64,
    pub total_equity: f64,
    pub open_positions_count: usize,
}

/// A simple momentum strategy (placeholder — real strategies use the existing tredo-autonomous agents).
pub struct MomentumStrategy;

#[async_trait]
impl Strategy for MomentumStrategy {
    fn name(&self) -> &str {
        "MomentumStrategy"
    }

    async fn evaluate(
        &self,
        symbol: &str,
        bar: &Bar,
        _context: &StrategyContext,
    ) -> StrategySignal {
        // Placeholder: always returns HOLD.
        // The real execution logic comes from tredo-autonomous's strategy_decision.rs.
        StrategySignal {
            symbol: symbol.to_string(),
            direction: SignalDirection::Hold,
            confidence: 0.0,
            entry_price: bar.close,
            stop_loss: bar.close * 0.98,
            take_profit: bar.close * 1.02,
            position_size_pct: 0.0,
            rationale: "MomentumStrategy placeholder — not active".to_string(),
        }
    }
}
