use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use std::sync::Mutex as StdMutex;
use tauri::State;
use tokio::sync::Mutex;
use tredo_autonomous::state::initialize_autonomous_system;
use tredo_autonomous::types::CotEntry;
use tredo_autonomous::AutonomousOrchestrator;
use tredo_core::{
    validate_trade_setup, Config, DisciplineRules, ExecutionEngine, MemoryStore, TradeDirection,
    TradeSetup,
};

// ── Process handles for spawned services ────────────────────────────────────
struct SystemProcesses {
    kronos: Option<std::process::Child>,
    orchestrator: Option<std::process::Child>,
}

impl SystemProcesses {
    fn new() -> Self {
        Self {
            kronos: None,
            orchestrator: None,
        }
    }
}

// ── Application State (holds in-process orchestrator for real COT data) ──────
struct AppState {
    config: Config,
    rules: DisciplineRules,
    execution: ExecutionEngine,
    processes: StdMutex<SystemProcesses>,
    orchestrator: Option<AutonomousOrchestrator>,
    /// Flat list of chain-of-thought entries generated by Tauri command handlers
    /// (the in-process orchestrator pushes to its own state.cot_store).
    tauri_cot_store: Arc<tokio::sync::RwLock<Vec<CotEntry>>>,
    tauri_cot_id: Arc<AtomicU64>,
}

impl AppState {
    fn new() -> Self {
        let config = Config::default();
        let rules = DisciplineRules::default();
        let memory =
            MemoryStore::new("tredo_memory.redb").expect("Failed to initialize memory store");
        let execution = ExecutionEngine::new(config.initial_balance, memory);
        Self {
            config,
            rules,
            execution,
            processes: StdMutex::new(SystemProcesses::new()),
            orchestrator: None,
            tauri_cot_store: Arc::new(tokio::sync::RwLock::new(Vec::new())),
            tauri_cot_id: Arc::new(AtomicU64::new(1)),
        }
    }
}

impl AppState {
    /// Push a COT entry generated by a Tauri command handler (not pipeline).
    async fn push_tauri_cot(
        &self,
        agent: &str,
        input: &str,
        action: &str,
        reason: &str,
        confidence: f64,
        symbol: Option<String>,
    ) {
        let id = self.tauri_cot_id.fetch_add(1, Ordering::Relaxed);
        let entry = CotEntry {
            id,
            chain_id: id,
            parent_id: None,
            agent: agent.to_string(),
            input: input.to_string(),
            action: action.to_string(),
            reason: reason.to_string(),
            confidence,
            timestamp: chrono::Utc::now().to_rfc3339(),
            symbol,
        };
        let mut store = self.tauri_cot_store.write().await;
        store.push(entry);
        if store.len() > 500 {
            store.remove(0);
        }
    }
}

/// Resolve the tredo workspace root directory.
fn project_root() -> std::path::PathBuf {
    let cwd = std::env::current_dir().unwrap_or_else(|_| std::path::PathBuf::from("."));
    if cwd.join("kronos_service").exists() {
        return cwd.clone();
    }
    if let Ok(exe) = std::env::current_exe() {
        let mut dir = exe
            .parent()
            .unwrap_or(std::path::Path::new("."))
            .to_path_buf();
        for _ in 0..6 {
            if dir.join("kronos_service").exists() {
                return dir;
            }
            dir = dir
                .parent()
                .unwrap_or(std::path::Path::new("."))
                .to_path_buf();
        }
    }
    cwd
}

// ── Tauri Commands ───────────────────────────────────────────────────────────

#[tauri::command]
async fn get_system_status(state: State<'_, Mutex<AppState>>) -> Result<String, String> {
    let app_state = state.lock().await;
    Ok(format!(
        "tredo Running | Initial Balance: {:.2} | Confluence Check: {}",
        app_state.config.initial_balance,
        if app_state.rules.use_confluence {
            "Enabled"
        } else {
            "Disabled"
        }
    ))
}

/// Start Kronos Forecasting Service + tredo Autonomous Orchestrator.
#[tauri::command]
async fn start_autonomous_system(
    state: State<'_, Mutex<AppState>>,
) -> Result<serde_json::Value, String> {
    let app_state = state.lock().await;
    let root = project_root();

    // ── 1. Start Kronos if not already responding ──────────────────────────
    let kronos_alive = reqwest::Client::new()
        .get("http://localhost:8000/docs")
        .timeout(std::time::Duration::from_millis(600))
        .send()
        .await
        .is_ok();

    let mut processes = app_state
        .processes
        .lock()
        .map_err(|_| "Process lock error".to_string())?;

    if let Some(ref mut child) = processes.kronos {
        if child.try_wait().map(|s| s.is_some()).unwrap_or(true) {
            processes.kronos = None;
        }
    }

    if !kronos_alive && processes.kronos.is_none() {
        let kronos_dir = root.join("kronos_service");
        match std::process::Command::new("python3")
            .arg("main.py")
            .current_dir(&kronos_dir)
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .spawn()
        {
            Ok(child) => {
                processes.kronos = Some(child);
                println!("[Tauri] ✅ Kronos service spawned");
            }
            Err(e) => {
                return Err(format!("Cannot start Kronos: {}", e));
            }
        }
    } else if kronos_alive {
        println!("[Tauri] ℹ Kronos already running");
    }

    // The real autonomous agent runs in the spawned subprocess (tredo-orchestrator binary).
    // That process starts its own Fast/Medium/Slow loops automatically and keeps
    // running even if you close this Tauri window.
    // The in-process orchestrator here is mainly for manual/debug commands and COT collection.
    // Once you click RUN SYSTEM, the background agent is in charge — no further human touch needed.

    // ── 2. Start subprocess Orchestrator (for background monitoring) ───────
    if let Some(ref mut child) = processes.orchestrator {
        if child.try_wait().map(|s| s.is_some()).unwrap_or(true) {
            processes.orchestrator = None;
        }
    }

    if processes.orchestrator.is_none() {
        let binary = root.join("target").join("debug").join("tredo-orchestrator");
        let spawn_result = if binary.exists() {
            std::process::Command::new(&binary)
                .current_dir(&root)
                .env("RUST_LOG", "info")
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .spawn()
        } else {
            // Fallback to cargo (slower, uses more resources, but works in dev)
            std::process::Command::new("cargo")
                .args(["run", "-p", "tredo-orchestrator"])
                .current_dir(&root)
                .env("RUST_LOG", "info")
                .stdout(std::process::Stdio::null())
                .stderr(std::process::Stdio::null())
                .spawn()
        };

        match spawn_result {
            Ok(child) => {
                processes.orchestrator = Some(child);
                println!("[Tauri] ✅ Autonomous Orchestrator subprocess launched.");
                println!(
                    "[Tauri]    The agent is now running independently (Fast/Medium/Slow loops)."
                );
                println!("[Tauri]    You can close this window — the background agent will keep trading (paper) on its own.");
                println!("[Tauri]    Use the Stop button or Ctrl+C in the terminal to shut it down cleanly.");
            }
            Err(e) => {
                return Err(format!("Cannot start Orchestrator: {}", e));
            }
        }
    }

    Ok(serde_json::json!({
        "status": "starting",
        "kronos":       processes.kronos.is_some() || kronos_alive,
        "orchestrator": processes.orchestrator.is_some(),
    }))
}

/// Stop all autonomous services.
#[tauri::command]
async fn stop_autonomous_system(state: State<'_, Mutex<AppState>>) -> Result<String, String> {
    let app_state = state.lock().await;
    let mut processes = app_state
        .processes
        .lock()
        .map_err(|_| "Process lock error".to_string())?;

    if let Some(ref mut child) = processes.kronos {
        let _ = child.kill();
        println!("[Tauri] 🛑 Kronos stopped");
    }
    processes.kronos = None;

    if let Some(ref mut child) = processes.orchestrator {
        let _ = child.kill();
        println!("[Tauri] 🛑 Orchestrator subprocess stopped");
    }
    processes.orchestrator = None;

    Ok("System stopped".to_string())
}

/// Get live health of all services (for UI status bar polling).
#[tauri::command]
async fn get_system_health(state: State<'_, Mutex<AppState>>) -> Result<serde_json::Value, String> {
    let app_state = state.lock().await;

    let (kronos_proc, orchestrator_proc) = {
        let mut processes = app_state
            .processes
            .lock()
            .map_err(|_| "Process lock error".to_string())?;

        let k = if let Some(ref mut c) = processes.kronos {
            c.try_wait().map(|s| s.is_none()).unwrap_or(false)
        } else {
            false
        };

        let o = if let Some(ref mut c) = processes.orchestrator {
            c.try_wait().map(|s| s.is_none()).unwrap_or(false)
        } else {
            false
        };

        (k, o)
    };

    let kronos_http = reqwest::Client::new()
        .get("http://localhost:8000/docs")
        .timeout(std::time::Duration::from_millis(400))
        .send()
        .await
        .is_ok();

    let kronos_up = kronos_proc || kronos_http;
    let orchestrator_up = orchestrator_proc;
    let in_process = app_state.orchestrator.is_some();

    Ok(serde_json::json!({
        "kronos":       kronos_up,
        "orchestrator": orchestrator_up,
        "llm":          true,
        "running":      kronos_up || orchestrator_up || in_process,
    }))
}

/// Get all chain-of-thought entries from the in-process orchestrator + Tauri command handlers.
#[tauri::command]
async fn get_cot_chains(state: State<'_, Mutex<AppState>>) -> Result<Vec<CotEntry>, String> {
    let app_state = state.lock().await;

    let mut all_entries = Vec::new();

    // From in-process orchestrator (if alive)
    if let Some(ref orch) = app_state.orchestrator {
        let pipe_entries = orch.state.cot_store.read().await;
        all_entries.extend(pipe_entries.clone());
    }

    // From Tauri command handlers (execute_trade, check_discipline, etc.)
    {
        let tauri_entries = app_state.tauri_cot_store.read().await;
        all_entries.extend(tauri_entries.clone());
    }

    // Sort by id ascending (chronological within each source; sources interleave)
    all_entries.sort_by_key(|e| e.id);

    Ok(all_entries)
}

#[tauri::command]
async fn execute_trade(
    symbol: String,
    direction_str: String,
    entry_price: f64,
    stop_loss: f64,
    take_profit: f64,
    state: State<'_, Mutex<AppState>>,
) -> Result<String, String> {
    let mut app_state = state.lock().await;

    let direction = match direction_str.to_lowercase().as_str() {
        "long" | "buy" => TradeDirection::Long,
        "short" | "sell" => TradeDirection::Short,
        _ => return Err("Invalid direction. Use 'long' or 'short'".to_string()),
    };

    let context = tredo_core::MarketContext {
        symbol: symbol.clone(),
        current_price: entry_price,
        high: entry_price * 1.01,
        low: entry_price * 0.99,
        previous_close: entry_price,
        timestamp: chrono::Utc::now(),
        daily_pnl: 0.0,
        equity: app_state.config.initial_balance,
        consecutive_losses: 0,
        is_red_folder_day: false,
        trend_direction: None,
    };

    let setup = TradeSetup::new(
        symbol.clone(),
        direction,
        entry_price,
        stop_loss,
        take_profit,
        context,
    );
    let check = validate_trade_setup(&setup.context, &app_state.rules);

    if !check.passed {
        app_state
            .push_tauri_cot(
                "DisciplineCore",
                &format!(
                    "Discipline check for {} {} @ {:.2}",
                    symbol, direction_str, entry_price
                ),
                "REJECTED",
                &check.reasons.join("; "),
                0.0,
                Some(symbol.clone()),
            )
            .await;
        return Err(format!("DISCIPLINE REJECTED: {}", check.reasons.join(", ")));
    }
    if entry_price <= 0.0 || stop_loss <= 0.0 || take_profit <= 0.0 {
        app_state
            .push_tauri_cot(
                "StrategyDecisionAgent",
                &format!(
                    "Price validation for {} {} @ {:.2}",
                    symbol, direction_str, entry_price
                ),
                "REJECTED",
                "Invalid prices — must be positive",
                0.0,
                Some(symbol.clone()),
            )
            .await;
        return Err(
            "INVALID PRICES: Entry, Stop Loss and Take Profit must be positive".to_string(),
        );
    }
    if (direction == TradeDirection::Long && stop_loss >= entry_price)
        || (direction == TradeDirection::Short && stop_loss <= entry_price)
    {
        app_state
            .push_tauri_cot(
                "StrategyDecisionAgent",
                &format!(
                    "Stop validation for {} {} @ {:.2} SL: {:.2}",
                    symbol, direction_str, entry_price, stop_loss
                ),
                "REJECTED",
                "Stop Loss must be below Entry for Long and above for Short",
                0.0,
                Some(symbol.clone()),
            )
            .await;
        return Err(
            "INVALID STOP: Stop Loss must be below Entry for Long and above for Short".to_string(),
        );
    }

    let rules = app_state.rules.clone();
    let result = match app_state.execution.execute_setup(setup, &rules).await {
        Ok(true) => {
            app_state
                .push_tauri_cot(
                    "ExecutionEngine",
                    &format!(
                        "Execute {} {} @ {:.2} | SL: {:.2} | TP: {:.2}",
                        symbol, direction_str, entry_price, stop_loss, take_profit
                    ),
                    "FILLED",
                    &format!(
                        "Trade executed: {} {} @ {:.2}",
                        symbol, direction_str, entry_price
                    ),
                    0.85,
                    Some(symbol.clone()),
                )
                .await;
            Ok(format!(
                "TRADE EXECUTED SUCCESSFULLY: {} @ {}",
                symbol, entry_price
            ))
        }
        Ok(false) => {
            app_state
                .push_tauri_cot(
                    "ExecutionEngine",
                    &format!("Execute {} {} @ {:.2}", symbol, direction_str, entry_price),
                    "PENDING",
                    "Paper mode — conditions not met",
                    0.5,
                    Some(symbol.clone()),
                )
                .await;
            Ok("Trade passed validation but engine conditions not met (paper mode).".to_string())
        }
        Err(e) => {
            app_state
                .push_tauri_cot(
                    "ExecutionEngine",
                    &format!("Execute {} {} @ {:.2}", symbol, direction_str, entry_price),
                    "ERROR",
                    &format!("Execution error: {}", e),
                    0.0,
                    Some(symbol.clone()),
                )
                .await;
            Err(format!("EXECUTION ERROR: {}", e))
        }
    };

    result
}

#[tauri::command]
async fn check_discipline(
    symbol: String,
    price: f64,
    state: State<'_, Mutex<AppState>>,
) -> Result<String, String> {
    let app_state = state.lock().await;
    let context = tredo_core::MarketContext {
        symbol: symbol.clone(),
        current_price: price,
        high: price * 1.01,
        low: price * 0.99,
        previous_close: price,
        timestamp: chrono::Utc::now(),
        daily_pnl: 0.0,
        equity: app_state.config.initial_balance,
        consecutive_losses: 0,
        is_red_folder_day: false,
        trend_direction: None,
    };
    let check = validate_trade_setup(&context, &app_state.rules);
    if check.passed {
        app_state
            .push_tauri_cot(
                "DisciplineCore",
                &format!("Discipline check for {} @ {:.2}", symbol, price),
                "PASS",
                "All discipline guards passed",
                0.9,
                Some(symbol),
            )
            .await;
        Ok("Trade setup passes Disciplined Core checks.".to_string())
    } else {
        app_state
            .push_tauri_cot(
                "DisciplineCore",
                &format!("Discipline check for {} @ {:.2}", symbol, price),
                "FAIL",
                &check.reasons.join(" | "),
                0.1,
                Some(symbol),
            )
            .await;
        Ok(format!(
            "Discipline violations: {}",
            check.reasons.join(" | ")
        ))
    }
}

#[tauri::command]
async fn run_backtest(state: State<'_, Mutex<AppState>>) -> Result<String, String> {
    let app_state = state.lock().await;
    let mut backtester = tredo_core::Backtester::new(app_state.rules.clone());
    let mut dummy_data = Vec::new();
    for i in 0..50 {
        dummy_data.push(tredo_core::MarketContext {
            symbol: "NIFTY".to_string(),
            current_price: 24000.0 + (i as f64 * 10.0),
            high: 24050.0,
            low: 23950.0,
            previous_close: 23980.0,
            timestamp: chrono::Utc::now(),
            daily_pnl: 0.0,
            equity: 100000.0,
            consecutive_losses: 0,
            is_red_folder_day: false,
            trend_direction: None,
        });
    }
    let result = backtester.run_simulation(dummy_data);

    app_state
        .push_tauri_cot(
            "Backtester",
            "Running 50-cycle backtest simulation",
            "COMPLETE",
            &format!(
                "Trades: {}, Win Rate: {:.1}%, P&L: ₹{:.2}, Max DD: {:.2}%",
                result.total_trades,
                result.win_rate * 100.0,
                result.total_pnl,
                result.max_drawdown * 100.0
            ),
            0.85,
            None,
        )
        .await;

    Ok(format!(
        "Backtest complete | Trades: {} | Win Rate: {:.1}% | Total P&L: ₹{:.2} | Max DD: {:.2}%",
        result.total_trades,
        result.win_rate * 100.0,
        result.total_pnl,
        result.max_drawdown * 100.0
    ))
}

#[tauri::command]
async fn fetch_live_stock_price(symbol: String) -> Result<f64, String> {
    let sym_upper = symbol.to_uppercase();
    let yahoo_symbol = match sym_upper.as_str() {
        "NIFTY" => "^NSEI",
        "RELIANCE" => "RELIANCE.NS",
        other => other,
    };
    let client = reqwest::Client::new();
    let url = format!(
        "https://query1.finance.yahoo.com/v8/finance/chart/{}?interval=1m&range=1d",
        yahoo_symbol
    );
    let resp: serde_json::Value = client
        .get(&url)
        .header(
            "User-Agent",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
        )
        .send()
        .await
        .map_err(|e| e.to_string())?
        .json()
        .await
        .map_err(|e| e.to_string())?;
    let price = resp["chart"]["result"][0]["meta"]["regularMarketPrice"]
        .as_f64()
        .ok_or_else(|| "regularMarketPrice field missing".to_string())?;
    Ok(price)
}

#[tauri::command]
async fn update_rules(
    use_confluence: bool,
    respect_session_timing: bool,
    state: State<'_, Mutex<AppState>>,
) -> Result<String, String> {
    let mut app_state = state.lock().await;
    app_state.rules.use_confluence = use_confluence;
    app_state.rules.respect_session_timing = respect_session_timing;
    app_state
        .push_tauri_cot(
            "MetaControl",
            "Update discipline rules",
            "UPDATED",
            &format!(
                "Confluence: {}, SessionTiming: {}",
                use_confluence, respect_session_timing
            ),
            0.9,
            None,
        )
        .await;
    Ok("Rules updated successfully".to_string())
}

#[tauri::command]
async fn trigger_orchestra_cycle(state: State<'_, Mutex<AppState>>) -> Result<String, String> {
    println!("[Tauri] === FULL ORCHESTRA CYCLE TRIGGERED FROM UI ===");

    // Clone the orchestrator out of the lock first, then release the lock
    let orch_clone = {
        let app_state = state.lock().await;
        app_state.orchestrator.clone()
    };

    if let Some(orch) = orch_clone {
        let dir = TradeDirection::Long;
        let sym = "NIFTY";
        let entry = 24500.0;
        let stop = 24200.0;
        let target = 25000.0;

        // Agentic call — only the symbol. The Tredo agent decides direction and its own levels
        // from market data + full analysis (indicators, debate, memory, rules).
        match orch.run_full_pipeline(&sym).await {
            Ok(summary) => {
                let action = summary
                    .final_signal
                    .map(|s| {
                        format!(
                            "{} {:.2}",
                            if s.direction == TradeDirection::Long {
                                "BUY"
                            } else {
                                "SELL"
                            },
                            s.entry_price
                        )
                    })
                    .unwrap_or_else(|| "HOLD".to_string());
                Ok(format!(
                    "ORCHESTRA CYCLE COMPLETE | Action: {} | Reason: {} | Duration: {}ms",
                    action, summary.reason, summary.total_duration_ms
                ))
            }
            Err(e) => Ok(format!("ORCHESTRA CYCLE ERROR: {}", e)),
        }
    } else {
        Ok("ORCHESTRA CYCLE COMPLETE | No in-process orchestrator — run start_autonomous_system first".to_string())
    }
}

// ── Main ─────────────────────────────────────────────────────────────────────
#[tokio::main]
async fn main() {
    env_logger::init_from_env(env_logger::Env::default().default_filter_or("info"));
    log::info!("[tredo UI] Starting Tauri application...");

    // Initialize in-process orchestrator
    let orch = initialize_autonomous_system()
        .await
        .expect("Failed to initialize autonomous orchestrator");

    let app_state = AppState {
        orchestrator: Some(orch),
        ..AppState::new()
    };

    tauri::Builder::default()
        .plugin(tauri_plugin_shell::init())
        .manage(Mutex::new(app_state))
        .invoke_handler(tauri::generate_handler![
            get_system_status,
            execute_trade,
            check_discipline,
            run_backtest,
            trigger_orchestra_cycle,
            fetch_live_stock_price,
            update_rules,
            start_autonomous_system,
            stop_autonomous_system,
            get_system_health,
            get_cot_chains,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
