use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Full context of a single agent decision and its outcome.
/// Every trade (BUY/SELL) generates one episode. HOLDs may optionally
/// generate episodes during reflection cycles for learning purposes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradingEpisode {
    pub episode_id: String,
    pub timestamp: DateTime<Utc>,
    pub symbol: String,

    /// Market state at decision time (price, pivots, volatility, news)
    pub market_state: MarketStateSnapshot,

    /// The agent's decision
    pub action: String, // "BUY" | "SELL" | "HOLD"
    pub entry_price: f64,
    pub stop_loss: f64,
    pub take_profit: f64,
    pub confidence: f64,

    /// Full reasoning trace from every agent that participated
    pub reasoning_trace: Vec<ReasoningStep>,

    /// Outcome — populated after trade closes (None if trade still open or HOLD)
    pub outcome: Option<TradeOutcome>,

    /// Post-trade reflection (generated by deep reflection in slow loop)
    pub reflection: Option<PostTradeReflection>,
}

/// Snapshot of all market context at the moment of decision.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketStateSnapshot {
    pub price: f64,
    pub pivot: f64,
    pub r1: f64,
    pub s1: f64,
    pub confluence: f64,
    pub trend: String,       // "Bullish" | "Bearish" | "Ranging" | "Neutral"
    pub volatility_24h: f64, // Approx 24h volatility % from OHLCV
    pub trend_strength: f64, // Slope from linear regression
    pub regime: String,      // "TrendingBull" | "TrendingBear" | "Volatile" | etc
    pub session_valid: bool,

    /// Economic calendar events active at decision time
    pub calendar_events: Vec<String>,

    /// Candlestick patterns detected (from Phase B)
    pub patterns: Vec<String>,

    /// News headlines (from Phase B)
    pub news_headlines: Vec<String>,

    /// Multi-timeframe context summary string for LLM
    pub multi_tf_summary: String,

    /// Agent's current trading mode
    pub trading_mode: String,

    /// Portfolio state at decision time
    pub portfolio_heat: f64,
    pub consecutive_losses: u32,
    pub daily_pnl_pct: f64,
}

impl MarketStateSnapshot {
    /// Generate a text summary for LLM prompts / episode queries.
    pub fn to_summary(&self) -> String {
        format!(
            "{} @ {:.2} | Pivot: {:.2} R1: {:.2} S1: {:.2} | Confluence: {:.1}% | Vol: {:.3} | Regime: {} | Mode: {}",
            self.trend, self.price, self.pivot, self.r1, self.s1,
            self.confluence * 100.0, self.volatility_24h, self.regime,
            self.trading_mode
        )
    }
}

/// A single reasoning step from one agent in the decision chain.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReasoningStep {
    pub agent_name: String,
    pub agent_tier: String,     // "main" | "sub" | "debate"
    pub input_summary: String,  // What the agent was asked
    pub output_summary: String, // What the agent decided/reported
    pub confidence: f64,        // Agent's confidence in its output
    pub duration_ms: u64,       // How long this step took
}

/// Outcome of a completed trade.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TradeOutcome {
    pub exit_price: f64,
    pub pnl: f64,
    pub pnl_pct: f64,
    pub exit_reason: String, // "stop_loss" | "take_profit" | "signal_reversal" | "manual" | "timeout" | "daily_goal_met"
    pub holding_period_secs: u64,
    pub max_unrealized_pnl: f64, // Best the position was at
    pub min_unrealized_pnl: f64, // Worst the position was at
    pub slippage: f64,           // Difference between expected and actual exit
}

/// Post-trade reflection generated by the deep reflection process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostTradeReflection {
    pub timestamp: DateTime<Utc>,
    pub lesson: String,
    pub violated_assumptions: Vec<String>,
    pub regret_score: f64, // 0.0 = perfect, 1.0 = terrible mistake
    pub what_went_wrong: Vec<String>,
    pub what_went_right: Vec<String>,
    pub suggested_rule_change: Option<String>, // Free-text suggestion
    pub should_alert: bool,                    // Flag for critical lessons
}
